### ISSUE TITLE
Database deadlock when multiple PA signatures are validated at the same time

### ISSUE THREAD

**Issue by hvge** [lime-company/powerauth-server#32]
When our mobile client is trying to create (`/pa/token/create`) a multiple tokens at the same time (for the same activation), then some of the requests ends with an unknown error:
```
{"status":"ERROR","responseObject":{"code":"ERROR_GENERIC","message":"error.unknown"}}
```
After a small investigation in the logs, we found out a database deadlock on the PA server:
```
2017-12-07 14:09:48.802  WARN 1 --- [nio-8080-exec-7] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1213, SQLState: 40001
2017-12-07 14:09:48.802 ERROR 1 --- [nio-8080-exec-7] o.h.engine.jdbc.spi.SqlExceptionHelper   : Deadlock found when trying to get lock; try restarting transaction
2017-12-07 14:09:48.802  INFO 1 --- [nio-8080-exec-7] o.h.e.j.b.internal.AbstractBatchImpl     : HHH000010: On release of batch it still contained JDBC statements
```

### UPDATE

The actual problem is not related to the tokens at all. Look for discussion below.

**Comment by hvge** [comment]
I didn't investigate scenario when different sessions are creating tokens at the same time, but it still looks like a serious issue. I think it may be related to "mysql magic".

**Comment by romanstrobl** [comment]
The root cause is update of activations. See deadlock information from MySQL - the two updates contain different counters.

------------------------
LATEST DETECTED DEADLOCK
------------------------
2017-12-07 14:42:13 0x7f6f340f5700
*** (1) TRANSACTION:
TRANSACTION 27298, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 5 lock struct(s), heap size 1136, 2 row lock(s), undo log entries 1
MySQL thread id 16, OS thread handle 140115591251712, query id 1312 172.18.0.5 powerauth updating
update pa_activation set activation_name='Juraj\'s test', activation_status=3, application_id=3, counter=58, device_public_key_base64='BIRG/+JA77m5FBu94hLizPC8L/1OLrgfM28WjCpUwlU0KXRmNoB1QzJjJNU+fJBEArjovhE1nQK9FvJqHtBlc4o=', extras=null, failed_attempts=0, master_keypair_id=1, max_failed_attempts=5, server_private_key_base64='AJQCyY/hqQrB1uZ4tvLSJGghAMDCgLCCw9ZS66idgyjH', server_public_key_base64='BCbjM7fIUDHkkKKG9rW8T1lzVzr8fA8OuPduaNMCnYepRw9yIi2wC7KnhJCtFZUqCzOFdsvhnbHBWOBaAZ8yVaQ=', timestamp_activation_expire='2017-12-01 15:57:54', timestamp_created='2017-12-01 15:55:54', timestamp_last_used='2017-12-07 14:42:13.796' where activation_id='970c81e8-f6ad-40f3-b23c-594b304be331'
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 26 page no 12 n bits 112 index PRIMARY of table `powerauth`.`pa_activation` trx id 27298 lock_mode X locks rec but not gap waiting
Record lock, heap no 15 PHYSICAL RECORD: n_fields 20; compact format; info bits 0
 0: len 30; hex 39373063383165382d663661642d343066332d623233632d353934623330; asc 970c81e8-f6ad-40f3-b23c-594b30; (total 36 bytes);
 1: len 6; hex 000000006857; asc     hW;;
 2: len 7; hex 62000001af064b; asc b     K;;
 3: len 11; hex 4e564353592d4c57463655; asc NVCSY-LWF6U;;
 4: len 11; hex 525849534b2d3435354f48; asc RXISK-455OH;;
 5: len 4; hex 80000003; asc     ;;
 6: len 12; hex 4a7572616a27732074657374; asc Juraj's test;;
 7: len 8; hex 8000000000000003; asc         ;;
 8: len 5; hex 6a7572616a; asc juraj;;
 9: SQL NULL;
 10: len 8; hex 8000000000000037; asc        7;;
 11: len 30; hex 424952472f2b4a4137376d354642753934684c697a5043384c2f314f4c72; asc BIRG/+JA77m5FBu94hLizPC8L/1OLr; (total 88 bytes);
 12: len 8; hex 8000000000000000; asc         ;;
 13: len 8; hex 8000000000000005; asc         ;;
 14: len 30; hex 414a514379592f687151724231755a3474764c534a476768414d4443674c; asc AJQCyY/hqQrB1uZ4tvLSJGghAMDCgL; (total 44 bytes);
 15: len 30; hex 4243626a4d3766495544486b6b4b4b473972573854316c7a567a72386641; asc BCbjM7fIUDHkkKKG9rW8T1lzVzr8fA; (total 88 bytes);
 16: len 8; hex 8000000000000001; asc         ;;
 17: len 5; hex 999e42fdf6; asc   B  ;;
 18: len 5; hex 999e42fe76; asc   B v;;
 19: len 5; hex 999e4ee666; asc   N f;;

*** (2) TRANSACTION:
TRANSACTION 27299, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
5 lock struct(s), heap size 1136, 2 row lock(s), undo log entries 1
MySQL thread id 15, OS thread handle 140115591517952, query id 1313 172.18.0.5 powerauth updating
update pa_activation set activation_name='Juraj\'s test', activation_status=3, application_id=3, counter=56, device_public_key_base64='BIRG/+JA77m5FBu94hLizPC8L/1OLrgfM28WjCpUwlU0KXRmNoB1QzJjJNU+fJBEArjovhE1nQK9FvJqHtBlc4o=', extras=null, failed_attempts=0, master_keypair_id=1, max_failed_attempts=5, server_private_key_base64='AJQCyY/hqQrB1uZ4tvLSJGghAMDCgLCCw9ZS66idgyjH', server_public_key_base64='BCbjM7fIUDHkkKKG9rW8T1lzVzr8fA8OuPduaNMCnYepRw9yIi2wC7KnhJCtFZUqCzOFdsvhnbHBWOBaAZ8yVaQ=', timestamp_activation_expire='2017-12-01 15:57:54', timestamp_created='2017-12-01 15:55:54', timestamp_last_used='2017-12-07 14:42:13.796' where activation_id='970c81e8-f6ad-40f3-b23c-594b304be331'
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 26 page no 12 n bits 112 index PRIMARY of table `powerauth`.`pa_activation` trx id 27299 lock mode S locks rec but not gap
Record lock, heap no 15 PHYSICAL RECORD: n_fields 20; compact format; info bits 0
 0: len 30; hex 39373063383165382d663661642d343066332d623233632d353934623330; asc 970c81e8-f6ad-40f3-b23c-594b30; (total 36 bytes);
 1: len 6; hex 000000006857; asc     hW;;
 2: len 7; hex 62000001af064b; asc b     K;;
 3: len 11; hex 4e564353592d4c57463655; asc NVCSY-LWF6U;;
 4: len 11; hex 525849534b2d3435354f48; asc RXISK-455OH;;
 5: len 4; hex 80000003; asc     ;;
 6: len 12; hex 4a7572616a27732074657374; asc Juraj's test;;
 7: len 8; hex 8000000000000003; asc         ;;
 8: len 5; hex 6a7572616a; asc juraj;;
 9: SQL NULL;
 10: len 8; hex 8000000000000037; asc        7;;
 11: len 30; hex 424952472f2b4a4137376d354642753934684c697a5043384c2f314f4c72; asc BIRG/+JA77m5FBu94hLizPC8L/1OLr; (total 88 bytes);
 12: len 8; hex 8000000000000000; asc         ;;
 13: len 8; hex 8000000000000005; asc         ;;
 14: len 30; hex 414a514379592f687151724231755a3474764c534a476768414d4443674c; asc AJQCyY/hqQrB1uZ4tvLSJGghAMDCgL; (total 44 bytes);
 15: len 30; hex 4243626a4d3766495544486b6b4b4b473972573854316c7a567a72386641; asc BCbjM7fIUDHkkKKG9rW8T1lzVzr8fA; (total 88 bytes);
 16: len 8; hex 8000000000000001; asc         ;;
 17: len 5; hex 999e42fdf6; asc   B  ;;
 18: len 5; hex 999e42fe76; asc   B v;;
 19: len 5; hex 999e4ee666; asc   N f;;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 26 page no 12 n bits 112 index PRIMARY of table `powerauth`.`pa_activation` trx id 27299 lock_mode X locks rec but not gap waiting
Record lock, heap no 15 PHYSICAL RECORD: n_fields 20; compact format; info bits 0
 0: len 30; hex 39373063383165382d663661642d343066332d623233632d353934623330; asc 970c81e8-f6ad-40f3-b23c-594b30; (total 36 bytes);
 1: len 6; hex 000000006857; asc     hW;;
 2: len 7; hex 62000001af064b; asc b     K;;
 3: len 11; hex 4e564353592d4c57463655; asc NVCSY-LWF6U;;
 4: len 11; hex 525849534b2d3435354f48; asc RXISK-455OH;;
 5: len 4; hex 80000003; asc     ;;
 6: len 12; hex 4a7572616a27732074657374; asc Juraj's test;;
 7: len 8; hex 8000000000000003; asc         ;;
 8: len 5; hex 6a7572616a; asc juraj;;
 9: SQL NULL;
 10: len 8; hex 8000000000000037; asc        7;;
 11: len 30; hex 424952472f2b4a4137376d354642753934684c697a5043384c2f314f4c72; asc BIRG/+JA77m5FBu94hLizPC8L/1OLr; (total 88 bytes);
 12: len 8; hex 8000000000000000; asc         ;;
 13: len 8; hex 8000000000000005; asc         ;;
 14: len 30; hex 414a514379592f687151724231755a3474764c534a476768414d4443674c; asc AJQCyY/hqQrB1uZ4tvLSJGghAMDCgL; (total 44 bytes);
 15: len 30; hex 4243626a4d3766495544486b6b4b4b473972573854316c7a567a72386641; asc BCbjM7fIUDHkkKKG9rW8T1lzVzr8fA; (total 88 bytes);
 16: len 8; hex 8000000000000001; asc         ;;
 17: len 5; hex 999e42fdf6; asc   B  ;;
 18: len 5; hex 999e42fe76; asc   B v;;
 19: len 5; hex 999e4ee666; asc   N f;;

**Comment by hvge** [comment]
Ok, we found out that the deadlock is not related to tokens, but the actual source of the problem is in signature validation. Looks like when multiple signatures for the same session are valid, then the updating internal counter causes this deadlock.

I've tried a check for valid password (`/pa/vault/unlock`) and the result is the same.

**Comment by romanstrobl** [comment]
I will investigate this bug in the backend.

**Comment by romanstrobl** [comment]
I wrote a test which fails with the deadlock in order to narrow down the problematic scenario:
https://github.com/lime-company/powerauth-server/commit/1b0c8ff59b923c7009a9865e63cb544ae9d8b17f

I also attach MySQL query log from the test run. The relevant queries start at 2018-02-15 16:04:42.161105. Notice the colum thread_id which can be used to differentiate between the two threads executing SQL queries.

[mysql_log.txt](https://github.com/lime-company/powerauth-server/files/1728229/mysql_log.txt)

The problem is that two transactions are started concurrently (autocommit is turned off). Both transactions try to update the same row in table pa_activation. First transaction succeeds (see commit in log at 16:04:42.208762 for thread 705, the second transaction in thread 706 is rolled back).

The exception occurs during the second update call:
com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction

Here is MySQL documentation related to deadlocks:
https://dev.mysql.com/doc/refman/5.7/en/innodb-deadlocks.html

I think we already use very small transactions and I do not think it is a good idea to turn off deadlock detection.

One possible approach to the problem could be to retry the failed transaction. However it does not seem to be a proper solution - and it could lead to invalid counter state in case the transaction order would not be preserved.

I think that a better solution would be to synchronize incoming API calls per activation ID. We could use e.g. the Command pattern to create a queue of incoming requests per activation ID and process one after another. When the activation IDs would differ for each request, there would be minimal slow down, the queue would have only 1 request per given activation ID, which would be immediately processed. In case of multiple parallel requests per activation ID the requests would be served on first come first serve basis.

If you have any other ideas how to resolve the issue let me know.

**Comment by romanstrobl** [comment]
I found out that the deadlock is related to locking the primary key in the pa_activation table.

One I drop the primary key in pa_activation table, the deadlock does not occur. It's definitely not something we would want to do, but at least it is some indication about the cause of the deadlock.

**Comment by petrdvorak** [comment]
... interesting.

**Comment by romanstrobl** [comment]
Ok, I think decoded the MySQL deadlock log. Both transactions run the UPDATE query on the same row, which requires getting an index lock for this row.

MySQL supports two types of row-level indexes:
* A shared (S) lock permits the transaction that holds the lock to read a row.
* An exclusive (X) lock permits the transaction that holds the lock to update or delete a row.

First transaction is waiting for exclusive lock (X) on row index.
Second transaction holds shared lock (S) on row index.
Second transaction is waiting for exclusive lock (X) on row index.

The deadlock seems to occur because neither first nor second transaction can get an exclusive lock on row index.

This also explains why the issue goes away when I drop the index on table pa_activation.

**Comment by romanstrobl** [comment]
I extracted additional information about active locks during the two transactions, see attached log.

[mysql_lock.log](https://github.com/lime-company/powerauth-server/files/1728792/mysql_lock.log)

**Comment by romanstrobl** [comment]
FWIW, I ran the test on PostgreSQL and there is no deadlock. I will confirm tomorrow with Oracle, but it seems that this issue is MySQL-specific.

**Comment by romanstrobl** [comment]
Here's a quick and dirty fix:

synchronized(activationId.intern()) {
            return behavior.getSignatureServiceBehavior().verifySignature(activationId, signatureType, signature, dataString, applicationKey, keyConversionUtilities);
        }

Perhaps if we would use a proper lock instead of actiovationId.intern(), this could work for preventing MySQL deadlocking itself on same row without degrading performance too much.

**Comment by romanstrobl** [comment]
And here is documentation from PostgreSQL on the same topic:

https://www.postgresql.org/docs/9.1/static/explicit-locking.html#LOCKING-DEADLOCKS

It would be better to avoid concurrent updates of the same activation row on application level, I think.

**Comment by romanstrobl** [comment]
There is no deadlock on Oracle either with same setup.
