### ISSUE TITLE
Duplicate log messages

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/powerauth-server#86]
Log messages are duplicated in PowerAuth server in default configuration. Perhaps it is caused by multiple logging libraries.

See screenshot.

<img width="1439" alt="screen shot 2018-06-08 at 16 06 00" src="https://user-images.githubusercontent.com/26658588/41162369-ee6d4f24-6b35-11e8-8f2a-162e230cba66.png">

**Comment by romanstrobl** [comment]
It seems that the problem is in the whole PowerAuth stack. It could be related to migration to Spring 2.0.0.

**Comment by petrdvorak** [comment]
FYI... here is this issue for duplicate logging:

spring-projects/spring-boot#11819

It is closed, but references this issue that should provide a fix for the duplicate logging:

spring-projects/spring-boot#8933

The issue was closed, but then reopened, mentions that proper fix should be implemented for Tomcat duplicate logging, and then closed again...

Maybe some of these issues contain any clue on what is going on...

**Comment by petrdvorak** [comment]
Btw I am not able to reproduce the issue with a simple demo app. :(

**Comment by romanstrobl** [comment]
I attach a simple project where logs are written twice on Tomcat. We can compare the projects to find out what is causing the bug.
 
[logging-test.zip](https://github.com/lime-company/powerauth-server/files/2091468/logging-test.zip)

**Comment by romanstrobl** [comment]
I raised an issue in Spring boot:
https://github.com/spring-projects/spring-boot/issues/13470
